---
- name: Configure tenant clusterroles
  hosts: all
  gather_facts: False

  vars_files:
    - vars/common.yml
    - vars/tenant.yml

  vars:
    - playbook_file_name: configure-tenant-clusterroles.yml

  roles:
    - configure_tenant_clusterroles
...
