---
- name: Configure Sudoer Commands
  hosts: all
  gather_facts: False

  vars_files:
    - vars/common.yml
    - vars/tenant.yml

  vars:
    - playbook_file_name: configure-sudo-commands.yml

  roles:
    - configure_sudo_commands
...
