---
- name: Configure Helm in target infras
  hosts: all
  gather_facts: False

  vars_files:
    - vars/common.yml

  vars:
    - playbook_file_name: configure-helm.yml

  roles:
    - configure_helm
...
